### ISSUE TITLE
web console not working with jdk 1.7

### ISSUE THREAD

**Issue by adelcourt** [clun/ff4j#133]
hi , 
i'm migrating from version 1.4 to 1.5.1  and  the web console cannot loading with jdk 1.7

java.lang.NoClassDefFoundError: java/util/Base64
	at org.ff4j.web.console.ImageProvider.fromFileToBase64(ImageProvider.java:95)
	at org.ff4j.web.console.ImageProvider.getImage(ImageProvider.java:119)
	at org.ff4j.web.console.ImageProvider.addImageToContext(ImageProvider.java:138)

we are actualy stuck  with jdk 1.7  (Weblogic  ...)  it's possible to use a more compliant base 64 encoder whith older environement  ?  
some possibility  : http://stackoverflow.com/questions/14413169/which-java-library-provides-base64-encoding-decoding

**Comment by clun** [comment]
We should be compliant with JDK1.6. I reinstall a JDK1.6 and change the IMageProvider to be compliant.
